version: 0.2

phases:
    pre_build:
        commands:
            - aws ecr get-login-password --region $region | docker login --username AWS --password-stdin $ECR_URL
            - IMAGE_REPO_NAME=$ECR_URL
    build:
        commands:     
            - export DOCKER_CLI_EXPERIMENTAL=enabled  
            - docker manifest create $IMAGE_REPO_NAME $IMAGE_REPO_NAME:latest-arm64 $IMAGE_REPO_NAME:latest-x86
            - docker manifest annotate --arch arm64 $IMAGE_REPO_NAME $IMAGE_REPO_NAME:latest-arm64
            - docker manifest annotate --arch amd64 $IMAGE_REPO_NAME $IMAGE_REPO_NAME:latest-x86
            - docker manifest push $IMAGE_REPO_NAME:latest
