version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region $region | docker login --username AWS --password-stdin $ECR_URL
      - IMAGE_REPO_NAME=$ECR_URL
  build:
    commands:        
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker push $IMAGE_REPO_NAME:$IMAGE_TAG